### ISSUE TITLE
Generating blank images

### ISSUE THREAD

**Issue by Kareeeeem** [quran/quran.com-images#14]
As salamu alaykum,

I followed the directions in the readme however the script is generating blank PNGs. I'm running debian stretch on a chromebook via crouton.

I had to install to following to get it to work to begin with: libgd-graph-perl, libtest-yaml-perl. 

Not really sure what else to mention. Sorry I cannot provide more information

**Comment by ahmedre** [comment]
wa3laikum alsalam,
two questions -
1. is the database setup properly (and can be accessed, i.e. they share the username/password/database name in `config/database.yaml`?)
2. are you getting any errors or warnings?
walsalam 3alaikum.

**Comment by Kareeeeem** [comment]
the database is set up properly but it is empty. (not sure how to fill it up).

I do not get warnings or errors, however I do see that all of the log statements in the code are commented out. (that allowed my to forgo the mojo::log depenency.)
