### ISSUE TITLE
Remove White stroke above ayah

### ISSUE THREAD

**Issue by Govar-Web** [quran/quran.com-images#27]
thanks for tell me what i need to edit to remove white stroke above ayat's?

**Comment by ahmedre** [comment]
which white strokes are you talking about?

**Comment by Govar-Web** [comment]
https://drive.google.com/file/d/1S62JXlA6X5DtWZTur72Yz-ubzCuaZW4o/view

**Comment by ahmedre** [comment]
i don't think there's anything we can do about this - this is an artifact of how the images are drawn and anti-aliasing and what not. we're not doing anything custom to cause this.

**Comment by Govar-Web** [comment]
Thank you bro, but sorry one more think, i'm kurdish speaker we have new
tafsir for quran (rebar tafsir), could you add it to quran android? thank
you.

https://play.google.com/store/apps/details?id=kDev.tafseri_rebar
