### ISSUE TITLE
How to generate images without ayat numbers? 

### ISSUE THREAD

**Issue by omar-adel** [quran/quran.com-images#34]
How to generate images without ayat numbers
I want to generate images without ayat numbers and also the database of rectangles of each aya and also rectangles with each aya number

**Comment by ahmedre** [comment]
you'll have to somehow exclude the glyph for the ayah numbers and not render it - you can modify the script to not draw it and leave a space instead.

**Comment by omar-adel** [comment]
thanks a lot
