### ISSUE TITLE
reqest

### ISSUE THREAD

**Issue by ens4dz** [quran/quran.com-images#4]
Salamo 3alaykom,
jazakom Allah khayran for this great project.
I do some testes to page 7 extracted from Android quran in my brother phone.

i used:
1-Gimp to replace white color with transparency one this make better look for black backgrounds.
2- http://compresspng.com/ to compress and compare (use thumbnails to activate the manual mode.)
in the future -inchaa Allah- , try to use other command line tools like pngcrush.
i didn't noticed any quality loss in 4.0" screen phone, 
the link :
https://mega.nz/#!hNRxxI4C!hZCcq8fqSPK0BkKlfXh6tmm0-I5_EvAB8xZA_W2i2kE
i really want to improve this great project ^_^ .

**Comment by ahmedre** [comment]
wa3laikum alsalam,
jazakAllah khairan. this project just has the fonts. i do think that if we were to run `pngcrush` on the images (as you suggested) that we could likely get better compression. insha'Allah can try that out in the future to decrease the download size.
walsalam 3alaikum.

**Comment by ahmedre** [comment]
made quran/quran_android#569. closing this one. jazakAllah khairan.
