### ISSUE TITLE
Page 585 image not render correctly on line 6

### ISSUE THREAD

**Issue by salahamassi** [quran/quran.com-images#43]
![585](https://user-images.githubusercontent.com/17902030/132069058-871dc76c-6e02-4240-84c4-c740a0b287c2.png)

Page 585 image not render correctly on line 6

**Comment by ahmedre** [comment]
this is very strange - i just tested and it properly renders for me. what values are you using when running it?

**Comment by salahamassi** [comment]
Sorry 
Sorry the problem occurred because I change the value of my $fontfactor property in Page.pm file.
