### ISSUE TITLE
Can I use this with react native (expo)?

### ISSUE THREAD

**Issue by AnasOnGit** [quran/quran.com-images#45]
Assalamualaikum everyone,
This is not an issue, I have a question, can I use this with react native (expo)?

I can see some SQL files and some docker files, but I am not sure how to use them.  I am not sure how docker works. Am I supposed to run this on the server?

Any help will be appreciated.
Jazakallah Khair

**Comment by ahmedre** [comment]
wa3laikum alsalam,
This repository is just to generate images and a database of x,y coordinates for where ayahs corresponding to the old madani mushaf. It's meant to run once, export its images and data, and not be used after that unless needed again in the future. The Docker container just gives an easier way to run it than having to set up Perl and the corresponding dependencies on the machine.
jazakumAllah khairan,
walsalam 3alaikum.

**Comment by AnasOnGit** [comment]
Thank you, brother, for explaining, I have one more question, should I package the exported images with the app or is there any other way of displaying the images without increasing the size of the app?

**Comment by ahmedre** [comment]
yes either bundle them with the app or put them on a server and have the application download the images.

**Comment by AnasOnGit** [comment]
Jazakallah Khair brother, I am losing this issue.
