### ISSUE TITLE
Is there any copyright or legal issues with fonts, if I use them?

### ISSUE THREAD

**Issue by taaaf11** [quran/quran.com-images#47]
Hey. There are font files in the 'https://github.com/quran/quran.com-images/tree/master/res/fonts' directory under this repository.

Is it okay if I download and use these fonts in my app? Are there any copyright issues or something?

**Comment by ahmedre** [comment]
The source of these is the [King Fahd Quran Complex](https://qurancomplex.gov.sa)and from what I know, they are legal to use for non-commercial purposes.

**Comment by taaaf11** [comment]
Okay. Just asking, if they are used for commercial purposes then?

**Comment by ahmedre** [comment]
no idea - you'd need to reach out to them and ask

**Comment by taaaf11** [comment]
I have got another question. I should have asked it earlier. Is this directory link is reliable? I mean, will these link break some day eventually? I am asking to use in my app.

Another question, if the app is open source, and I get donations from it, then will it come under the commercial use of these fonts?

**Comment by ahmedre** [comment]
While I have no plans of moving them, there are never guarantees - you should host them yourself and/or put them somewhere you control to be safe.

Not sure tbh, you can go to their website and see if you find anything there about it.

**Comment by taaaf11** [comment]
Okay. Thank you for assistance!
